import { api, iso, launch, newUser, BASE } from "./lib.mjs";
const S = process.argv[2];
const browser = await launch();
const nowTokyo = () => { const p = new Intl.DateTimeFormat("en-GB", { timeZone: "Asia/Tokyo", hour: "2-digit", minute: "2-digit", hour12: false }).format(new Date()).split(":"); return Number(p[0]) * 60 + Number(p[1]); };
const todayTokyo = new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Tokyo" }).format(new Date());
for (const kind of ["mobile", "desktop"]) {
  const { ctx, page } = await newUser(browser, kind);
  page.on("console", (m) => { if (m.type() === "error") console.log(`[${kind}]`, m.text().slice(0, 300)); });
  const trip = await api(page, "POST", "/api/trips", { title: "도쿄 3박 4일", destination: "도쿄", timezone: "Asia/Tokyo", startDate: todayTokyo, endDate: iso(3), travelerCount: 2, currency: "JPY", budgetAmount: 300000 });
  const d1 = trip.days[0].id;
  const n = nowTokyo();
  const add = (b) => api(page, "POST", `/api/trips/${trip.id}/items`, { dayId: d1, durationMinutes: 60, ...b });
  const clamp = (m) => Math.max(0, Math.min(m, 1430));
  await add({ title: "아사쿠사 센소지", category: "CULTURE", startMinute: clamp(n - 240), durationMinutes: 90, latitude: 35.7148, longitude: 139.7967 });
  await add({ title: "점심 · 텐동", category: "FOOD", startMinute: clamp(n - 130), latitude: 35.7127, longitude: 139.7962 });
  await add({ title: "시부야 스카이", category: "SIGHTSEEING", startMinute: clamp(n - 20), durationMinutes: 90, latitude: 35.6585, longitude: 139.7022 });
  await add({ title: "오모테산도 쇼핑", category: "SHOPPING", startMinute: clamp(n + 90), latitude: 35.6672, longitude: 139.7085 });
  await add({ title: "저녁 · 이자카야", category: "FOOD", startMinute: clamp(n + 180), durationMinutes: 90, latitude: 35.6933, longitude: 139.6994 });
  const it = await api(page, "GET", `/api/trips/${trip.id}/itinerary`);
  for (const i of it.days[0].items.slice(0, 2)) await api(page, "PATCH", `/api/trips/${trip.id}/items/${i.id}`, { status: "DONE" });
  await page.goto(`${BASE}/dashboard`);
  await page.waitForTimeout(1200);
  await page.screenshot({ path: `${S}/${kind}-p4-today.png`, fullPage: true });
  await page.goto(`${BASE}/trips/${trip.id}/companion`);
  await page.waitForTimeout(800);
  await page.screenshot({ path: `${S}/${kind}-p4-empty.png` });
  await page.getByRole("button", { name: "지금 너무 피곤해" }).click();
  await page.getByRole("button", { name: "일정 줄이기" }).waitFor({ timeout: 20000 });
  await page.waitForTimeout(500);
  await page.screenshot({ path: `${S}/${kind}-p4-fatigue.png`, fullPage: true });
  await page.getByRole("button", { name: "일정 줄이기" }).click();
  await page.getByText("적용했어요").waitFor();
  await page.getByLabel("AI에게 메시지 보내기").fill("여기 너무 좋다. 1시간 더 있을래");
  await page.keyboard.press("Enter");
  await page.getByRole("button", { name: "자동 조정" }).waitFor({ timeout: 20000 });
  await page.waitForTimeout(500);
  await page.screenshot({ path: `${S}/${kind}-p4-extend.png`, fullPage: true });
  await ctx.close();
}
await browser.close();
console.log("done");
